### ISSUE TITLE
The backend for follow/unfollow user

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#100]
Once the user follow someone. we take to update our tables in the database accordingly. The tables which will be affected are users, followers and following. #71

**Comment by RobertBeaudenon** [comment]
I started implementing the followUser backend, i'm going to push that code in a new branch
I'm also handling the case where we can't follow a user twice if we are already following him

**Comment by RobertBeaudenon** [comment]
The only thing that is left to do is the Unfollow User.

It is basically almost the same code with some minor modifications when dealing with the database:
- instead of inserting new rows in the 'follower' and 'following' tables we will be deleting them
-instead of incrementing by 1 the number of followers and following in the 'user' table we will be decrementing by 1

**Comment by AlainJobs** [comment]
All done.
