### ISSUE TITLE
20 test case to run.

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#153]
Sprint 3 requires us to run _at least_ 20 test cases. The exact way of proceeding to this task should be discussed in groups. Apparently, the lectures slides talk about those test cases.

**Comment by mohanadarafe** [comment]
# How it works?
Alright please pay attention to this post! The Travis CI is up and running, fully connected to our Travis account. Now comes the time to write 20 test cases testing the liability of our core features!

## What you will need
In order to do so, here are some things you need to have:

- Node version 10+
- Check your node version by typing `node -v` in the terminal
- Comment **BELOW** two test cases you will be doing (since we are 10).
- Test cases must be unique and taken from user stories.

## Once you finished coding
Once you figured out the test cases you will do, head over to the `tests.js` file and start coding! In order to test the validity, `console.log()` a success and failure message. Once you push, notify @mohanadarafe and I will check for you if you test case passed. 

## Example
The following will output on the Travis CI console **test failed!**. 
```
var test = false;
if(test)
    console.log("test passed!");
else
    console.log("test failed!");
```

## Please get it done by Tuesday!

**Comment by mohanadarafe** [comment]
### My test cases:

- Making sure you **cannot like a Wit twice**
- Making sure you may not **post an empty Wit**

**Comment by csbduzi** [comment]
### My test cases:

- Making sure that the **user cannot like his own Wit**
- Making sure that the **user may not delete Wits of other users**

**Comment by Hambrsoom** [comment]
My test cases:
- Making sure that the user can n't post a very long wit.
- Making sure that the user  can post a wit.

**Comment by bernzclav** [comment]
My test cases:

- Making sure that the user can like a wit from someone he is following.
- Making sure that the user can delete his own wit.

**Comment by daphneaugier** [comment]
My test cases : 

- Making sure that the user can follow someone 
- Making sure that the user cannot follow him/herself

**Comment by AlainJobs** [comment]
My test cases:

- Making sure that the user can **properly follow and unfollow** another user.
- Making sure that the user **cannot follow his own account** (already implemented and good in backend).

**Comment by DariushN** [comment]
My test cases:

- Making sure that the user can search another user.
- Making sure that the user cannot search himself.

**Comment by CarenRizk** [comment]
My test cases:

- making sure a user can't like a reply twice

- making sure a user ca't post an empty reply

**Comment by HussainWitwit** [comment]
### My test cases:

- Making sure a user can like a Wit of someone they are not following
- Making sure a user can unlike a wit

**Comment by mohanadarafe** [comment]
Front end & Back end tests fully functional with Travis CI
<img width="1054" alt="6b90baabab9a07f1d3801d62d1a260fa" src="https://user-images.githubusercontent.com/34899555/53828604-2017b600-3f4c-11e9-9702-2a96b862a05a.png">
