### ISSUE TITLE
Informing the user of some errors

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#44]
It is necessary to inform the user for some errors to be able to know what's wrong:
Cases:
- For register: if the user uses an username or email that's already been used by someone else, they won't be able to register. It is important to know that they can't use these info.
- For login: in case if they input the wrong email or password, it is necessary to tell them that.
- For forget password: in case if the user doesn't put the correct email.

**Comment by Hambrsoom** [comment]
There was a small problem with the login verification. I fixed it. However, we are still missing the verification for the forget password. @AlainJobs Can u start it ? Then, I will debug it.

**Comment by AlainJobs** [comment]
Hi guys, thanks for letting me know and fixing the issue (what was it by the way?). I helped Chris with the implementation of the validation with the forget password already. He was trying to push his work but he's facing some backend issues. Also, we still need to consolidate the form validation with the errors message given by the database (hampic). I'll work on that before the deadline as well as the profile page.

**Comment by Hambrsoom** [comment]
@csbduzi and @AlainJobs , I believe you guys are almost done from this part ? if so, can you share an image of how does it look like ?

**Comment by csbduzi** [comment]
The bug is fixed and the events with the triggered alerts are functional.
Here are the pictures of the scenarios.
 
1) When the user enters an email that corresponds to an email of a user in the database.

![img_5735](https://user-images.githubusercontent.com/46238950/52731769-8a13ef80-2f8c-11e9-8c04-a37ff359f03c.JPG)

2) When the user enters an email that does not correspond to an email of a user in the database. 

![img_5738](https://user-images.githubusercontent.com/46238950/52732129-6d2bec00-2f8d-11e9-8b8c-b0560eecb955.JPG)

**Comment by Hambrsoom** [comment]
It looks good. Good job Guys 💯
