### ISSUE TITLE
having access to everything

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#54]
There is a major bug conerning the security of our web app is that a user can access the timeline without the need to register. It is necessary to prevent anyone from doing that by using AuthGuard.

**Comment by DariushN** [comment]
I have added route guards that prevent users that are not signed in to access pages such as timeline and profile, and instead redirect them to the login page. I also changed the menu toolbar so that it reacts to the condition that the user is logged in. For example, I have hidden the "timeline" and "profile" navbar items to users that are not signed in.
