### ISSUE TITLE
showing if the user liked a wit or not

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#56]
We need to take in consideration two situations:
- If the user has liked a specific wit so we don't allow him to like it again.
- if he/she didn't like it and we allow them to like it only once 
#39

**Comment by Hambrsoom** [comment]
So, how did you guys implement this ? @mohanadarafe  and @CarenRizk

**Comment by CarenRizk** [comment]
Checking if the user is in the list of who liked a wit, if he is then we redirect directly to unlike the wit instead of liking it. To make it more user friendly if the user have not liked the wit before it will show a heart and when the wit is liked by a user it shows a broken heart which indicates that clicking will unlike a wit.
